from __future__ import annotations

import math

TB3_MIN_LINEAR_MPS: float = 0.0
TB3_MAX_LINEAR_MPS: float = 0.22
TB3_MIN_ANGULAR_RADPS: float = -2.84
TB3_MAX_ANGULAR_RADPS: float = 2.84

LIDAR_SECTOR_COUNT: int = 36
LIDAR_MIN_RANGE_M: float = 0.12
LIDAR_MAX_RANGE_M: float = 3.5

STATE_WINDOW_SIZE: int = 4

EGO_FEATURE_COUNT: int = 3
FORMATION_FEATURE_COUNT: int = 2

KINEMATIC_FEATURE_COUNT: int = EGO_FEATURE_COUNT + FORMATION_FEATURE_COUNT

STATE_FEATURE_COUNT: int = EGO_FEATURE_COUNT + FORMATION_FEATURE_COUNT + LIDAR_SECTOR_COUNT

ACTION_DIM: int = 2
ACTION_FEATURE_COUNT: int = ACTION_DIM

DISCRIMINATOR_FEATURE_COUNT: int = STATE_FEATURE_COUNT + ACTION_DIM
AGENT_STATE_ACTION_DIM: int = DISCRIMINATOR_FEATURE_COUNT

MIN_HEADING_RAD: float = -math.pi
MAX_HEADING_RAD: float = math.pi
FORMATION_ERROR_MIN_M: float = -2.0
FORMATION_ERROR_MAX_M: float = 2.0

CONTROL_PERIOD_SEC: float = 0.1
DEFAULT_GRID_FREQUENCY_HZ: float = 10.0

COLLISION_THRESHOLD_M: float = 0.15
SLOWDOWN_THRESHOLD_M: float = 0.50
SLOWDOWN_SCALE: float = 0.50
FORMATION_LOST_DISTANCE_M: float = 2.0
RECOVERY_LIDAR_FOCUS_RANGE_M: float = 1.5
FRONT_ARC_DEG: float = 30.0

DEFAULT_ANOMALY_WINDOW_SEC: float = 0.5
DEFAULT_MAX_INTERPOLATION_GAP_SEC: float = 0.2
